env:
  es2024: true
  node: true
plugins:
  - jsdoc
  - '@typescript-eslint'
extends:
  - 'eslint:recommended'
  - 'plugin:jsdoc/recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    impliedStrict: true
rules:
  jsdoc/tag-lines: 0
  jsdoc/no-defaults: 0
  indent:
    - error
    - tab
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
    - omitLastInOneLineBlock: true
      omitLastInOneLineClassBody: true
settings:
  jsdoc:
    mode: typescript
    structuredTags:
      template:
        name: namepath-defining
        type: true
    tagNamePreference:
      augments:
        message: >-
          @extends is to be used over @augments as it is more evocative of
          classes than @augments
        replacement: extends